### ISSUE TITLE
Print item name in multiple lines with keeping it well formatted!

### ISSUE THREAD

**Issue by khaledkhj** [thedathoudarya/WAGU-data-in-table-view#4]
Thank you for this great solution,

I am currently running into one problem, where I have items with a long name and i want to print them with no grid, but the code provided trim the name and print one line only!

Can you please help in how to print the item name in multiple lines?

Thank you in advance.

**Comment by thedathoudarya** [comment]
I assume you are using Table class to build your table, and what you asked is something I have missed to implement in. But, you can always use Block, and create your own table structure. For an example, if you have 100 cells in your table (including columns) you need to loop through row data and append blocks to form a table. You can give a height to the Blocks, so that block data will appear as multiline texts.
